version: '3.9'
services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  app:
    restart: on-failure
    build: ./build
    ports:
      - '81:8000'
  nginx:
    build: ./nginx
    ports:
    - '80:80'
    depends_on:
    - app